name: Sync translation files CSV and JSON

on:
  push:
    branches:    
      - 'main'


jobs:
  sync_translation:
    name: 'Sync translation files CSV and JSON'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        name: Check out repository
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install deps
        run: yarn install
#       - name: Run eslint
#         run: yarn lint
      - name: Run json to csv script'
#         working-directory: client
        run: |
          chmod +x "../scripts/json2csvAction"
          "../scripts/json2csvAction"
        shell: bash
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional, but recommended
          # Defaults to "Apply automatic changes"
          commit_message: Automated Change | Converting JSON

          # Optional branch name where commit should be pushed to.
          # Defaults to the current branch.
          branch: main

          # # Optional. Used by `git-commit`.
          # # See https://git-scm.com/docs/git-commit#_options
          # commit_options: '--no-verify --signoff'

          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          # file_pattern: src/*.js tests/*.js *.php

          # Optional local file path to the repository
          # Defaults to the root of the repository
          # repository: .

          # Optional commit user and author settings
          # commit_user_name: My GitHub Actions Bot # defaults to "GitHub Actions"
          # commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
          # commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run

        env:
          CI: true
